### ISSUE TITLE
Can I Create a PR with a Function that "Fixes" List in Case of Duplicates?

### ISSUE THREAD

**Issue by pacarvalho** [brendon/acts_as_list#333]
I have noticed that under some peculiar situations it is possible to end up with a list that contains duplicate positions in acts_at_list. The duplicate positions cause unexpected behaviors to acts_as_list and sometimes leads to errors. 

Would it be OK if I created a PR with a function that fixes lists that contain duplicate positions? 

It could be done by arbitrarily choosing an order for the items with duplicated positions (there is no way of knowing which should come first with respect to one another) and moving other items out of the way. 

Related to #76 #317

**Comment by DanielHeath** [comment]
I've got an efficient solution for this for postgres (using window functions) and mysql (using connection variables), but sqlite lacks a nice way to do this.

**Comment by brendon** [comment]
Hi @DanielHeath, this looks promising. I see it in your PR :) The only thing I can think of is that it'd be nice to tidy up these code forks for specific database backends into seperate files so they can be maintained more easily?

**Comment by DanielHeath** [comment]
Happy to split it up, but would appreciate some guidance about what shape it should take - I tend to favor "too much code" rather than "where's the code", when making that sort of judgement call so I'm less familiar with good patterns for this kind of split.

**Comment by brendon** [comment]
Hehe, yea, I'm not 100% sure I like the current project structure with all those `definers`. I like the way `ancestry` structures their code. But that's a project for another day.

I'm thinking perhaps when loading methods into the model, we could do a check for the current database adapter (on the model - as some projects will have different databases on different models), we then include a file based on whether it's sqlite, mysql or postgres that have identical methods with different implementations?

**Comment by brendon** [comment]
Closing this for now. Let me know if you want to look at it again. Check out https://github.com/brendon/positioning as an alternative to `acts_as_list` that uses an advisory lock to prevent corruption.
