### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by GeorgeA93** [brendon/acts_as_list#361]
There have been a lot of changes since the previous v0.9.19 release in March. One, in particular, has fixed a bunch of deprecation warnings for Rails 6 users 🙌

Are you able to create a new release please? If not do you have any idea as to when you will be creating one?

Thanks!

**Comment by brendon** [comment]
Hi @GeorgeA93, @swanandp plans to release a new version (probably 1.0.0) as he's handed over ownership of the project to me. I'm not sure when that will happen exactly but hopefully in the next week or so :)

**Comment by swanandp** [comment]
Done! Released `1.0.0`.
