### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by RobinClowers** [brendon/acts_as_list#369]
https://info.pagnis.in/acts_as_list/ is a 404, did the docs move somewhere else?

**Comment by brendon** [comment]
Hi @RobinClowers, I wasn't aware they were even there :D Where is that link published?

The docs are here though: https://www.rubydoc.info/gems/acts_as_list

**Comment by RobinClowers** [comment]
It's set as the website in the github repo preferences. Thanks!

**Comment by brendon** [comment]
Lol all good. I've fixed that up :)
