### ISSUE TITLE
`nil` Scope Condition Causes Loss of Scope

### ISSUE THREAD

**Issue by sshaw** [brendon/acts_as_list#390]
Version: 1.0.3
Active Record: 5.2.3

```rb
# Foo
acts_as_list scope: :owner

# ...

Foo.create(:owner => Owner.first)
```

Adds the following SQL criteria:
```SQL
WHERE "foos"."owner_id" = $1 AND ("foos"."position" IS NOT NULL)
```

But when scoping to a column (sorta like the example in the docs):
```rb
# Foo
acts_as_list scope: [:owner, :discarded_at => nil] 

# ...

Foo.create(:owner => Owner.first)
```

The following criteria is added; 
```SQL
WHERE "foos"."owner_id" IS NULL AND "foos"."discarded_at" = $1 AND ("foos"."position" IS NOT NULL)
--- $1 = ["discarded_at", nil]
```

**Comment by brendon** [comment]
Without checking, I think you need to add `_id` to any columns within an array scope (it's a hangup from the old days where you could omit the `_id` from a symbol scope and it would be added on):

`acts_as_list scope: [:owner_id, :discarded_at => nil]`

Let me know if that doesn't work though.

If it interests you, here's where scopes are defined: https://github.com/brendon/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/scope_method_definer.rb

**Comment by sshaw** [comment]
Hi, thanks. I thought that was attempted but I do see that it is working now with `_id`.
