### ISSUE TITLE
Tests for Ruby 2.7 and 3.0

### ISSUE THREAD

**Issue by QWYNG** [brendon/acts_as_list#392]
Hi! Thank you for great gem.
Could you please add Ruby 3.0 and 2.7 tests as shown in the ranked-model commit below?
https://github.com/mixonic/ranked-model/pull/174
https://github.com/mixonic/ranked-model/pull/168

I didn't think it would be a good idea for me to just copy and paste this code and I will be a contributor, since it's mostly the result of @aried3r efforts!

**Comment by aried3r** [comment]
Hey @QWYNG, while I don't use this gem at my current work project, I'm perfectly fine if you copy and paste what I did for ranked-model. :)

Cheers

**Comment by QWYNG** [comment]
@aried3r 
hmm, Thanks for your kind offer. I appreciate it.
created PR #393

**Comment by brendon** [comment]
All good @QWYNG, I'll look to merge your PR.
