### ISSUE TITLE
Limiting the list size

### ISSUE THREAD

**Issue by Tao-Galasse** [brendon/acts_as_list#395]
Hi!

I'm looking for a way to set a limit on a list ; for example, let's say I have a user who can only have 5 ordered profiles.

Does the gem include a feature to handle this behaviour all by itself, or should I do it myself on the application layer ?

Thank you! 😊

**Comment by brendon** [comment]
Hi @Tao-Galasse, there isn't any kind of limitation system in `acts_as_list`. You'd probably need to implement this as a database constraint (for it to be completely safe), or a `before_save` to abort the save after a certain limit. There might be other better ways than this too, that's just off the top of my head :)
